version: "3.6"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: streamsaver:v1
    ports:
      - 1718:1718
    networks:
      - br_backend
    volumes:
      # Host directory : Directory inside container
      - /media/download:/media/download # for download storage
      - hls_data:/media/hls  # for storing streaming data
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: streaming_nginx
    networks:
      - br_backend
    ports:
      - 1719:1719
    depends_on:
      - backend
    volumes:
      - hls_data:/media/hls

networks:
  br_backend:
    driver: bridge

volumes:
  hls_data:
    driver_opts:
      type: none
      device: /media/download/hls
      o: bind